
enum Category {
  livingRoom,
  bedRoom,
  kitchen,
  diningRoom,
}
enum Country {
  afghanistan("Afghanistan"),
  albania("Albania"),
  algeria("Algeria"),
  andorra("Andorra"),
  angola("Angola"),
  antiguaAndBarbuda("Antigua and Barbuda"),
  argentina("Argentina"),
  armenia("Armenia"),
  australia("Australia"),
  austria("Austria"),
  azerbaijan("Azerbaijan"),
  bahamas("Bahamas"),
  bahrain("Bahrain"),
  bangladesh("Bangladesh"),
  barbados("Barbados"),
  belarus("Belarus"),
  belgium("Belgium"),
  belize("Belize"),
  benin("Benin"),
  bhutan("Bhutan"),
  bolivia("Bolivia"),
  bosniaAndHerzegovina("Bosnia and Herzegovina"),
  botswana("Botswana"),
  brazil("Brazil"),
  brunei("Brunei"),
  bulgaria("Bulgaria"),
  burkinaFaso("Burkina Faso"),
  burundi("Burundi"),
  caboVerde("Cabo Verde"),
  cambodia("Cambodia"),
  cameroon("Cameroon"),
  canada("Canada"),
  centralAfricanRepublic("Central African Republic"),
  chad("Chad"),
  chile("Chile"),
  china("China"),
  colombia("Colombia"),
  comoros("Comoros"),
  congoDemocraticRepublic("Congo, Democratic Republic"),
  congoRepublic("Congo, Republic"),
  costaRica("Costa Rica"),
  coteDIvoire("Côte d'Ivoire"),
  croatia("Croatia"),
  cuba("Cuba"),
  cyprus("Cyprus"),
  czechRepublic("Czech Republic"),
  denmark("Denmark"),
  djibouti("Djibouti"),
  dominica("Dominica"),
  dominicanRepublic("Dominican Republic"),
  ecuador("Ecuador"),
  egypt("Egypt"),
  elSalvador("El Salvador"),
  equatorialGuinea("Equatorial Guinea"),
  eritrea("Eritrea"),
  estonia("Estonia"),
  eswatini("Eswatini"),
  ethiopia("Ethiopia"),
  fiji("Fiji"),
  finland("Finland"),
  france("France"),
  gabon("Gabon"),
  gambia("Gambia"),
  georgia("Georgia"),
  germany("Germany"),
  ghana("Ghana"),
  greece("Greece"),
  grenada("Grenada"),
  guatemala("Guatemala"),
  guinea("Guinea"),
  guineaBissau("Guinea-Bissau"),
  guyana("Guyana"),
  haiti("Haiti"),
  honduras("Honduras"),
  hungary("Hungary"),
  iceland("Iceland"),
  india("India"),
  indonesia("Indonesia"),
  iran("Iran"),
  iraq("Iraq"),
  ireland("Ireland"),
  israel("Israel"),
  italy("Italy"),
  jamaica("Jamaica"),
  japan("Japan"),
  jordan("Jordan"),
  kazakhstan("Kazakhstan"),
  kenya("Kenya"),
  kiribati("Kiribati"),
  koreaNorth("Korea, North"),
  koreaSouth("Korea, South"),
  kosovo("Kosovo"),
  kuwait("Kuwait"),
  kyrgyzstan("Kyrgyzstan"),
  laos("Laos"),
  latvia("Latvia"),
  lebanon("Lebanon"),
  lesotho("Lesotho"),
  liberia("Liberia"),
  libya("Libya"),
  liechtenstein("Liechtenstein"),
  lithuania("Lithuania"),
  luxembourg("Luxembourg"),
  madagascar("Madagascar"),
  malawi("Malawi"),
  malaysia("Malaysia"),
  maldives("Maldives"),
  mali("Mali"),
  malta("Malta"),
  marshallIslands("Marshall Islands"),
  mauritania("Mauritania"),
  mauritius("Mauritius"),
  mexico("Mexico"),
  micronesia("Micronesia"),
  moldova("Moldova"),
  monaco("Monaco"),
  mongolia("Mongolia"),
  montenegro("Montenegro"),
  morocco("Morocco"),
  mozambique("Mozambique"),
  myanmar("Myanmar"),
  namibia("Namibia"),
  nauru("Nauru"),
  nepal("Nepal"),
  netherlands("Netherlands"),
  newZealand("New Zealand"),
  nicaragua("Nicaragua"),
  niger("Niger"),
  nigeria("Nigeria"),
  northMacedonia("North Macedonia"),
  norway("Norway"),
  oman("Oman"),
  pakistan("Pakistan"),
  palau("Palau"),
  panama("Panama"),
  papuaNewGuinea("Papua New Guinea"),
  paraguay("Paraguay"),
  peru("Peru"),
  philippines("Philippines"),
  poland("Poland"),
  portugal("Portugal"),
  qatar("Qatar"),
  romania("Romania"),
  russia("Russia"),
  rwanda("Rwanda"),
  saintKittsAndNevis("Saint Kitts and Nevis"),
  saintLucia("Saint Lucia"),
  saintVincentAndGrenadines("Saint Vincent and the Grenadines"),
  samoa("Samoa"),
  sanMarino("San Marino"),
  saoTomeAndPrincipe("Sao Tome and Principe"),
  saudiArabia("Saudi Arabia"),
  senegal("Senegal"),
  serbia("Serbia"),
  seychelles("Seychelles"),
  sierraLeone("Sierra Leone"),
  singapore("Singapore"),
  slovakia("Slovakia"),
  slovenia("Slovenia"),
  solomonIslands("Solomon Islands"),
  somalia("Somalia"),
  southAfrica("South Africa"),
  southSudan("South Sudan"),
  spain("Spain"),
  sriLanka("Sri Lanka"),
  sudan("Sudan"),
  suriname("Suriname"),
  sweden("Sweden"),
  switzerland("Switzerland"),
  syria("Syria"),
  taiwan("Taiwan"),
  tajikistan("Tajikistan"),
  tanzania("Tanzania"),
  thailand("Thailand"),
  timorLeste("Timor-Leste"),
  togo("Togo"),
  tonga("Tonga"),
  trinidadAndTobago("Trinidad and Tobago"),
  tunisia("Tunisia"),
  turkey("Turkey"),
  turkmenistan("Turkmenistan"),
  tuvalu("Tuvalu"),
  uganda("Uganda"),
  ukraine("Ukraine"),
  unitedArabEmirates("United Arab Emirates"),
  unitedKingdom("United Kingdom"),
  unitedStates("United States"),
  uruguay("Uruguay"),
  uzbekistan("Uzbekistan"),
  vanuatu("Vanuatu"),
  vaticanCity("Vatican City"),
  venezuela("Venezuela"),
  vietnam("Vietnam"),
  yemen("Yemen"),
  zambia("Zambia"),
  zimbabwe("Zimbabwe");

  final String name;
  const Country(this.name);
}

class CartItem {
  CartItem({
    required this.id,
    required this.productName,
    required this.property,
    required this.price,
    required this.imageUrl,
    required this.category,
    required this.quantity
  }); 
  final int id;
  final String productName;
  final String property;
  final double price;
  final String imageUrl;
  final Category category;
  int quantity;
  
}

class CartBucket {

  CartBucket({required this.items, required this.category});

 
  CartBucket.forCategory(List<CartItem> allItems, this.category)
      : items = allItems.where((item) => item.category == category).toList();

  final Category category;
  final List<CartItem> items;

  double get totalCost {
    double sum = 0;
    for (final item in items) {
      sum += item.price;
    }
    return sum;
  }
}
